/* Generated By:JavaCC: Do not edit this line. TestBalancedParserConstants.java */
package ajeffrey.teaching.test;

public interface TestBalancedParserConstants {

  int EOF = 0;
  int OPEN = 1;
  int CLOSE = 2;
  int PERIOD = 3;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\".\"",
  };

}
