/* Generated By:JavaCC: Do not edit this line. SizeRequestParserConstants.java */
package ajeffrey.teaching.size.event;

public interface SizeRequestParserConstants {

  int EOF = 0;
  int QUIT = 1;
  int CRLF = 2;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"QUIT\"",
    "<CRLF>",
  };

}
