/* Generated By:JavaCC: Do not edit this line. SizeResponseParserConstants.java */
package ajeffrey.teaching.size.event;

public interface SizeResponseParserConstants {

  int EOF = 0;
  int OK = 1;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"OK\"",
  };

}
