/* Generated By:JavaCC: Do not edit this line. HTTPParserConstants.java */
package ajeffrey.teaching.http.server.parser;

public interface HTTPParserConstants {

  int EOF = 0;
  int GET = 1;
  int HTTP = 2;
  int SPACE = 3;
  int COLON = 4;
  int DOT = 5;
  int SLASH = 6;
  int UNDERSCORE = 7;
  int MINUS = 8;
  int CRLF = 9;
  int DIGIT = 10;
  int ALPHABETIC = 11;
  int CHAR = 12;
  int NUMBER = 13;
  int STRING = 14;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<GET>",
    "<HTTP>",
    "\" \"",
    "\":\"",
    "\".\"",
    "\"/\"",
    "\"_\"",
    "\"-\"",
    "<CRLF>",
    "<DIGIT>",
    "<ALPHABETIC>",
    "<CHAR>",
    "<NUMBER>",
    "<STRING>",
  };

}
